### ISSUE TITLE
Can't pass FocusNode to ReactivePhoneFormField

### ISSUE THREAD

**Issue by Pitazzo** [artflutter/reactive_forms_widgets#42]
I'm trying to pass a `FocusNode` to a `ReactivePhoneFormField` instance but I keep getting an exception. Here is a minimum example of a widget suffering from this issue:
```
class MXAReactivePhoneInput extends StatefulWidget {
  final String formControlName;
  final TitleData? title;
  final bool suggestAutofill;

  const MXAReactivePhoneInput({
    Key? key,
    required this.formControlName,
    this.title = const TitleData(
      title: 'Número de teléfono',
      icon: Icons.phone,
    ),
    this.suggestAutofill = false,
  }) : super(key: key);

  @override
  State<MXAReactivePhoneInput> createState() => _MXAReactivePhoneInputState();
}

class _MXAReactivePhoneInputState extends State<MXAReactivePhoneInput> {
  late FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        FieldTitle(title: widget.title),
        SizedBox(
          height: 100,
          child: ReactivePhoneFormField(
            focusNode: _focusNode,
            formControlName: widget.formControlName,
          ),
        ),
      ],
    );
  }

  @override
  void dispose() {
    super.dispose();
    _focusNode.dispose();
  }
}
```

When my `MXAReactivePhoneInput` get rendered, I get following trace:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building ReactivePhoneFormField<dynamic>(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#eefe0]], state: _ReactivePhoneFormFieldState<dynamic>#6ecdc):
A PhoneController was used after being disposed.

Once you have called dispose() on a PhoneController, it can no longer be used.
The relevant error-causing widget was
ReactivePhoneFormField<dynamic>
lib/…/forms/mxa_reactive_phone_input.dart:44
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:114
#1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:120
#2      ChangeNotifier.addListener
package:flutter/…/foundation/change_notifier.dart:173
#3      _PhoneFormFieldState.initState
package:phone_form_field/…/widgets/phone_form_field.dart:235
#4      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:4893
#5      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4729
...     Normal element mounting (12 frames)
#17     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#18     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6422
#19     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6433
...     Normal element mounting (15 frames)
#34     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#35     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6422
#36     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6433
#37     _ViewportElement.mount
package:flutter/…/widgets/viewport.dart:222
...     Normal element mounting (110 frames)
#147    Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#148    Element.updateChild
package:flutter/…/widgets/framework.dart:3524
#149    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4780
#150    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4928
#151    Element.rebuild
package:flutter/…/widgets/framework.dart:4477
#152    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2659
#153    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#154    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:363
#155    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#156    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1081
#157    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:995
#161    _invoke (dart:ui[/hooks.dart:151:10]())
#162    PlatformDispatcher._drawFrame (dart:ui[/platform_dispatcher.dart:308:5]())
#163    _drawFrame (dart:ui[/hooks.dart:115:31]())
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A PhoneController was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by vasilich6107** [comment]
@Pitazzo fixed in reactive_phone_form_field 0.2.1
